/**
 * build-seed.ts
 *
 * Emits seed/seed.sql: an idempotent upsert of the HYROX pack and its 27 skills
 * into the Skill Me `skills` / `packs` / `pack_skills` tables.
 *
 * SCHEMA CONFIRMATION (Section 9 dependency)
 * ------------------------------------------
 * The live skillshelf Supabase `public.skills` and `public.packs` schema was
 * confirmed via the Supabase MCP `list_tables` on 2026-06-21. Findings that
 * shape this seed (and that MUST be re-confirmed before running against any
 * other project, or if the schema drifts):
 *
 *   - PK `id` is a server-generated uuid (default gen_random_uuid()). The stable
 *     natural key is the UNIQUE `slug`. Therefore the upsert conflict target is
 *     `(slug)`, not `(id)` as Section 9 phrased it. pack_skills rows resolve the
 *     uuids by joining on slug.
 *   - `category` is constrained to a fixed enum
 *     (coding|writing|research|productivity|data|design|business|personal[,mixed]).
 *     Fitness has no native bucket, so every skill maps to `personal` and the
 *     HYROX domain category is carried in `subcategory` (e.g. "hyrox-running").
 *   - `skills.skill_content` stores the installable SKILL.md (frontmatter+body).
 *   - Independent content: `verified` is false and `author` is neutral; the pack
 *     `name` uses the neutral display name because brand_authorized is false.
 *
 * The one genuine placeholder is the repository URL (REPO_URL): replace OWNER
 * with the real GitHub org/repo before publishing.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, loadAllSkills, GREEN } from './_lib.ts';

const REPO_URL = 'https://github.com/aouellets/hyrox-claude-skills';
const CATALOG_CATEGORY = 'personal'; // DB enum bucket for fitness content
// Catalog author string. Also the key the Skill Me partner-logo registry
// (lib/partners.ts) matches on to render the licensed HYROX wordmark.
const NEUTRAL_AUTHOR = 'HYROX Performance';

function sqlStr(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlTextArray(values: string[]): string {
  if (values.length === 0) return "'{}'";
  const inner = values.map((v) => '"' + v.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"').join(',');
  return `'{${inner}}'`;
}

interface Inventory {
  pack: string;
  skills: Array<{
    id: string;
    name: string;
    description: string;
    category: string;
    risk_level: string;
    requires_current_rules: boolean;
  }>;
}

interface Manifest {
  id: string;
  display_name: string;
  neutral_display_name: string;
  brand_authorized: boolean;
  purpose: string;
  skill_ids: string[];
  notes: string;
}

function run(): void {
  const inventory = JSON.parse(readFileSync(join(ROOT, 'skill-inventory.json'), 'utf8')) as Inventory;
  const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8')) as Manifest;
  const brand = JSON.parse(readFileSync(join(ROOT, 'assets', 'brand', 'brand-authorization.json'), 'utf8')) as {
    authorized: boolean;
  };

  const { skills } = loadAllSkills();
  const rawById = new Map(skills.map((s) => [s.id, s.raw]));

  const packName = manifest.brand_authorized && brand.authorized ? manifest.display_name : manifest.neutral_display_name;
  const packVerified = manifest.brand_authorized && brand.authorized;

  const lines: string[] = [];
  lines.push('-- ===========================================================================');
  lines.push('-- seed/seed.sql — AUTOGENERATED by scripts/build-seed.ts. Do not edit by hand.');
  lines.push('--');
  lines.push('-- Idempotent upsert of the HYROX performance pack + 27 skills into the');
  lines.push('-- Skill Me catalog (public.skills, public.packs, public.pack_skills).');
  lines.push('--');
  lines.push('-- SCHEMA CONFIRMATION: columns below were confirmed against the live skillshelf');
  lines.push('-- Supabase project on 2026-06-21 (list_tables). The conflict target is the');
  lines.push('-- UNIQUE slug (id is a server-generated uuid). category is constrained to a');
  lines.push("-- fixed enum, so fitness content maps to 'personal' with the HYROX domain");
  lines.push('-- category carried in subcategory. RE-CONFIRM before targeting another project.');
  lines.push('--');
  lines.push(`-- Non-affiliation: ${manifest.notes}`);
  lines.push('-- ===========================================================================');
  lines.push('');
  lines.push('begin;');
  lines.push('');

  // --- skills ---
  lines.push('-- ---- skills ---------------------------------------------------------------');
  for (const s of inventory.skills) {
    const raw = rawById.get(s.id);
    if (!raw) {
      console.error(`build-seed: no SKILL.md content found for "${s.id}"`);
      process.exit(1);
    }
    const tags = ['hyrox', 'fitness-racing', s.category, `risk:${s.risk_level}`];
    if (s.requires_current_rules) tags.push('rules-dependent');
    lines.push(
      `insert into skills (slug, name, description, category, subcategory, source_url, author, skill_content, tags, free, verified, updated_at) values (`,
    );
    lines.push(`  ${sqlStr(s.id)},`);
    lines.push(`  ${sqlStr(s.name)},`);
    lines.push(`  ${sqlStr(s.description)},`);
    lines.push(`  ${sqlStr(CATALOG_CATEGORY)},`);
    lines.push(`  ${sqlStr('hyrox-' + s.category)},`);
    lines.push(`  ${sqlStr(REPO_URL + '/tree/main/skills/' + s.id)},`);
    lines.push(`  ${sqlStr(NEUTRAL_AUTHOR)},`);
    lines.push(`  ${sqlStr(raw)},`);
    lines.push(`  ${sqlTextArray(tags)},`);
    lines.push(`  true,`);
    lines.push(`  false,`);
    lines.push(`  now()`);
    lines.push(`) on conflict (slug) do update set`);
    lines.push(`  name = excluded.name,`);
    lines.push(`  description = excluded.description,`);
    lines.push(`  category = excluded.category,`);
    lines.push(`  subcategory = excluded.subcategory,`);
    lines.push(`  source_url = excluded.source_url,`);
    lines.push(`  author = excluded.author,`);
    lines.push(`  skill_content = excluded.skill_content,`);
    lines.push(`  tags = excluded.tags,`);
    lines.push(`  free = excluded.free,`);
    lines.push(`  updated_at = now();`);
    lines.push('');
  }

  // --- pack ---
  lines.push('-- ---- pack -----------------------------------------------------------------');
  const packDescription = `${manifest.purpose}\n\n${manifest.notes}`;
  const packTagline = 'Periodized coaching for the 8-run / 8-station fitness race: assessment, goal-time modeling, pacing, stations, simulations, taper, and post-race analysis.';
  lines.push(
    `insert into packs (slug, name, tagline, description, author, author_url, category, tags, repo_url, free, verified, updated_at) values (`,
  );
  lines.push(`  ${sqlStr(manifest.id)},`);
  lines.push(`  ${sqlStr(packName)},`);
  lines.push(`  ${sqlStr(packTagline)},`);
  lines.push(`  ${sqlStr(packDescription)},`);
  lines.push(`  ${sqlStr(NEUTRAL_AUTHOR)},`);
  lines.push(`  ${sqlStr(REPO_URL)},`);
  lines.push(`  ${sqlStr(CATALOG_CATEGORY)},`);
  lines.push(`  ${sqlTextArray(['hyrox', 'fitness-racing', 'endurance', 'strength-and-conditioning', 'race-prep'])},`);
  lines.push(`  ${sqlStr(REPO_URL)},`);
  lines.push(`  true,`);
  lines.push(`  ${packVerified ? 'true' : 'false'},`);
  lines.push(`  now()`);
  lines.push(`) on conflict (slug) do update set`);
  lines.push(`  name = excluded.name,`);
  lines.push(`  tagline = excluded.tagline,`);
  lines.push(`  description = excluded.description,`);
  lines.push(`  author = excluded.author,`);
  lines.push(`  author_url = excluded.author_url,`);
  lines.push(`  category = excluded.category,`);
  lines.push(`  tags = excluded.tags,`);
  lines.push(`  repo_url = excluded.repo_url,`);
  lines.push(`  free = excluded.free,`);
  lines.push(`  updated_at = now();`);
  lines.push('');

  // --- pack_skills (idempotent: clear then re-insert resolving uuids by slug) ---
  lines.push('-- ---- pack_skills (associate every skill with the pack, in routing order) --');
  lines.push(`delete from pack_skills where pack_id in (select id from packs where slug = ${sqlStr(manifest.id)});`);
  lines.push('insert into pack_skills (pack_id, skill_id, position)');
  lines.push('select p.id, s.id, v.position');
  lines.push('from (values');
  const valueRows = manifest.skill_ids.map((id, i) => `  (${sqlStr(id)}, ${i})`).join(',\n');
  lines.push(valueRows);
  lines.push(') as v(slug, position)');
  lines.push('join skills s on s.slug = v.slug');
  lines.push(`join packs p on p.slug = ${sqlStr(manifest.id)};`);
  lines.push('');
  lines.push('commit;');
  lines.push('');

  const outPath = join(ROOT, 'seed', 'seed.sql');
  writeFileSync(outPath, lines.join('\n'));
  console.log(`${GREEN('✔')} build-seed wrote ${inventory.skills.length} skill upserts -> seed/seed.sql`);
}

run();
