/**
 * build-inventory.ts
 *
 * Generates skill-inventory.json (the canonical catalog seed source) from the
 * skill frontmatter. This is the single intermediate artifact build-seed.ts
 * consumes, so the seed never reads SKILL.md directly.
 *
 * Output shape:
 *   { pack, skills: [{ id, name, description, category, risk_level, requires_current_rules }] }
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, loadAllSkills, GREEN } from './_lib.ts';

interface InventorySkill {
  id: string;
  name: string;
  description: string;
  category: string;
  risk_level: string;
  requires_current_rules: boolean;
}

function run(): void {
  const { skills, parseErrors } = loadAllSkills();
  if (parseErrors.length) {
    console.error('Cannot build inventory: some skills failed to parse:');
    for (const pe of parseErrors) console.error(`  [${pe.id}] ${pe.error}`);
    process.exit(1);
  }

  const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8')) as {
    id: string;
    skill_ids: string[];
  };

  const inventorySkills: InventorySkill[] = skills
    .map((s) => ({
      id: s.id,
      name: String(s.frontmatter.name),
      description: String(s.frontmatter.description),
      category: String(s.frontmatter.category),
      risk_level: String(s.frontmatter.risk_level),
      requires_current_rules: s.frontmatter.requires_current_rules === true,
    }))
    .sort((a, b) => a.id.localeCompare(b.id));

  // cross-check against the manifest's declared skill_ids
  const inventoryIds = new Set(inventorySkills.map((s) => s.id));
  const manifestIds = new Set(manifest.skill_ids);
  for (const id of manifestIds) {
    if (!inventoryIds.has(id)) {
      console.error(`manifest lists skill "${id}" but no such skill folder exists`);
      process.exit(1);
    }
  }
  for (const id of inventoryIds) {
    if (!manifestIds.has(id)) {
      console.error(`skill "${id}" exists but is not listed in manifest.skill_ids`);
      process.exit(1);
    }
  }

  const inventory = {
    pack: manifest.id,
    generated_note: 'AUTOGENERATED by scripts/build-inventory.ts from skill frontmatter. Do not edit by hand.',
    skill_count: inventorySkills.length,
    skills: inventorySkills,
  };

  const outPath = join(ROOT, 'skill-inventory.json');
  writeFileSync(outPath, JSON.stringify(inventory, null, 2) + '\n');
  console.log(`${GREEN('✔')} build-inventory wrote ${inventorySkills.length} skills -> skill-inventory.json`);
}

run();
